### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Lukemul6** [MoneyKiddMo/SupremeMobileNewItem#1]
Nice looking code! I am guessing it hasn't been completed yet? I don't see anywhere to enter discord webhook info etc.

**Comment by MoneyKiddMo** [comment]
Yes, if you were to view the update logs you could clearly see I stated that serialization was completed, and the full build should be done soon. I'm looking to have it completed in the next 2 or 3 days.

**Comment by Lukemul6** [comment]
My bad!
